### PR TITLE
Moved Round method to Data_Engine

### LINKED ISSUE #308: Move Round method to BHoM Engine - Data Engine
As per the title. Ensure method is versioned.

### PR DESCRIPTION
**Pull request by robinflyman**
Closes #308 

Moved Round method to Data_Engine and fixed some problems that occurred after deleting the float-method.

### CODE REVIEW

**Comment by robinflyman** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by robinflyman** [comment]
@BHoMBot fix project file ref. 6504956490

**Comment by robinflyman** [comment]
@BHoMBot check versioning

**Comment by robinflyman** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6508094358

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6508120378

**Pull request merged**
